### ISSUE TITLE
Error on "Speed Up" Transaction on OP Mainnet

### ISSUE THREAD

**Issue by MSilb7** [rainbow-me/browser-extension#1046]
<img width="248" alt="image" src="https://github.com/rainbow-me/browser-extension/assets/4006780/f8d454b2-6326-452c-b294-1844d866d413">

1. Submitted a transaction (hanging on sending)
2. Right-clicked to open in block explorer -> Etherscan returns 'can not find tx hash'
3. Right click to speed up & submit
4. Error pops up.

Both MM and Rainbow are installed on Brave desktop, but the tx was sent through the Rainbow extension.

**Comment by DanielSinclair** [comment]
Thanks for reporting! Investigating

**Comment by DanielSinclair** [comment]
The reliability of this feature should be significantly stronger with our `v1.3.57` release today.
