### ISSUE TITLE
Improvement Suggestions: Settings and Feature Additions

### ISSUE THREAD

**Issue by 0xc0le** [rainbow-me/browser-extension#1096]
Hi! Loving the browser extension. I have used it to onboard several new users to crypto! While taking a fresh look at Rainbow, I put together several suggestions for improvements that I think could be beneficial:

**Improvements:**
- Users should have the option to add/change RPC endpoints. This could be added under the ‘Transactions’ option within the wallet settings. With this addition, users could also have the ability to add new networks not currently supported by Rainbow. 
- Users should have the option to manually hide tokens. Currently, the only option for hiding tokens is a built-in ‘Hide tokens under $1 balance’ setting. 
- Currently, tokens are sorted by highest balance. In my opinion, users should have the option to sort by network as well. 
- The browser extension should have a discover page to mimic the mobile app. The discover page could direct users to the official websites of certain dApps.

**Comment by DanielSinclair** [comment]
Hey @0xc0le. Thanks for the feedback and suggestions! Custom Networks and a "Hide" feature for Tokens will be rolling out within the next few weeks, actually! We'll continue to think more about token-by-network filtering; I think we can make progress here. We don't currently have plans for a direct parallel to the app's Discover section, but you will start to see more and more dApps marked with a verification badge or warnings as you connect and interact with them across the Web to ensure that you're not interacting with a fake or malicious dApp.
