### ISSUE TITLE
Missing extensionId in chrome.runtime.sendMessage()

### ISSUE THREAD

**Issue by kakashigr** [rainbow-me/browser-extension#1117]
I'm testing on a local Dapp on latest Chrome on MacOS. Metamask and Coinbase extensions work fine. Rainbow is also able to connect to the page and sign a message. But for every other action, like minting a token, it fails. I see this error spamming my console:

`inpage.js:1 Uncaught (in promise) TypeError: Error in invocation of runtime.sendMessage(optional string extensionId, any message, optional object options, optional function callback): chrome.runtime.sendMessage() called from a webpage must specify an Extension ID (string) for its first argument.`

And for an example mint function, I get this error:

`Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"REMOVED_FOR_GITHUB","to":"REMOVED_FOR_GITHUB","data":"REMOVED_FOR_GITHUB","accessList":null}, error={}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at _Logger.makeError (index.ts:269:28)
    at _Logger.throwError (index.ts:281:20)
    at checkError (json-rpc-provider.ts:66:16)
    at Web3Provider.<anonymous> (json-rpc-provider.ts:642:20)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.ts:20:1)`

The exact same action and calldata works fine on metamask and coinbase.

**Comment by brunobar79** [comment]
Thanks for reporting the issue! Would you be able to provide us with an example so we can repro? We have a decent amount of tests that should cover this so I think it's gonna be quite hard otherwise for us to find the issue and fix it. LMK!

**Comment by DanielSinclair** [comment]
@kakashigr Are you still seeing this issue?
