### ISSUE TITLE
Enable Hardware Wallet support on Firefox

### ISSUE THREAD

**Issue by jcmonte** [rainbow-me/browser-extension#1260]
What was the reason for disabling hardware wallet support on Firefox? Is it possible to bring that back anytime soon? I'd prefer firefox over chrome for privacy reasons.

https://github.com/rainbow-me/browser-extension/pull/907

**Comment by DanielSinclair** [comment]
Firefox currently does not support U2F, WebHID, or WebUSB to connect to a hardware wallet with Manifest v3 extensions, so we unfortunately are limited in what we can support right now. When this changes, we'll add support as soon as we can!
