### ISSUE TITLE
Simulation token amount "unlimited"

### ISSUE THREAD

**Issue by Ncookiez** [rainbow-me/browser-extension#1269]
There seems to be an overflow (maybe?) where simulations of token transfers, approvals, etc. show as "unlimited" when sufficiently large. I've only noticed this with tokens with 18 decimals as of now.

**Examples:**

Approving 1 WETH (18 decimals):
<img src="https://github.com/rainbow-me/browser-extension/assets/22108522/20d38236-a5bc-4480-9958-2be57ab8f814" width="300">

Withdrawing 10 DAI (18 decimals) from a contract:
<img src="https://github.com/rainbow-me/browser-extension/assets/22108522/1c51efe7-3b48-4407-a3e3-1ba1e855ced7" width="300">

Approving 100 USDC (6 decimals):
<img src="https://github.com/rainbow-me/browser-extension/assets/22108522/842fb3f9-8103-4725-91f4-19c7712b0273" width="300">

**Comment by DanielSinclair** [comment]
@Ncookiez Thanks for spotting! We'll investigate this later today

**Comment by AlexBHarley** [comment]
We've noticed this again, tiny approvals (ie 0.0000001 of an 18 decimal token) also show in the simulation as unlimited.

Can try it out on https://renzo.superbridge.app for an example, bridging ezETH from Base to OP
