### ISSUE TITLE
Browser Extension won't connect to any websites

### ISSUE THREAD

**Issue by git615btc** [rainbow-me/browser-extension#1270]
Using fresh Brave browser profile with only rainbow wallet installed. 
Have transferred all my wallets over from metamask. 
Disabled brave wallets. 

Rainbow will never connect to any website, including opensea, uniswap, etc. 

When selecting what wallet to connect, on selecting "metamask" I will get redirected to download metamask rather than rainbow wallet opening. Likewise when I select "browser wallet". 

Is there a way to force Rainbow wallet to open and connect?

**Comment by DanielSinclair** [comment]
By default, Rainbow acts as the default wallet, and this can always be toggled off in Settings. Some dApps will implement their wallet connection differently and will sometimes always favor MetaMask with their connect buttons, which is unfortunately out of our control, but we can always help relay fixes to those teams if you see a particular isolated issue with a dapp. 

<img width="363" alt="Screenshot 2023-12-29 at 1 02 21 AM" src="https://github.com/rainbow-me/browser-extension/assets/4412473/6a845efc-a477-4e33-8f80-8da61dd8f53e">

For Brave browser specifically, the built-in Brave Wallet will act as the super-default, and you may need to adjust your Web3 Settings in the browser to resolve this. That sounds like the issue you're seeing. Here are instructions to favor "Extensions" over the built-in wallet: https://support.brave.com/hc/en-us/articles/15241705110157-Adjusting-the-Default-Wallet

Let me know if you're still seeing this problem!

**Comment by git615btc** [comment]
Hi Daniel,

Thanks for your reply. 
I've disabled Brave wallet as default and have selected use extension as default and it still won't work. Rabby and metamask work perfectly so I can't figure out why it can't detect metamask as an option. 
Is there anything else I can do to force it to recognise rainbow wallet?

**Comment by DanielSinclair** [comment]
@git615btc I tested this flow again and unfortunately cannot reproduce. Do you happen to have any other extensions active, like Stello? Sometimes these extensions can also interfere.
