### ISSUE TITLE
Connection issues with Remix

### ISSUE THREAD

**Issue by smartcontracts** [rainbow-me/browser-extension#1276]
Getting a few weird issues when using Rainbow + remix.ethereum.org + OP Sepolia

I can connect fine but for some reason Remix doesn't detect any accounts at first

<img width="447" alt="Screenshot 2024-01-02 at 5 37 43 PM" src="https://github.com/rainbow-me/browser-extension/assets/14298799/e95e1b18-299c-433e-91e5-f50d1abad744">

I have to go to the extension, click "switch wallet", then click again on the wallet that is already connected.

<img width="447" alt="Screenshot 2024-01-02 at 5 38 08 PM" src="https://github.com/rainbow-me/browser-extension/assets/14298799/e205c929-78d2-4f4a-9709-a5f584778ae4">

I'm then able to see the wallet but Remix thinks the wallet has no balance (it does).

<img width="447" alt="Screenshot 2024-01-02 at 5 38 56 PM" src="https://github.com/rainbow-me/browser-extension/assets/14298799/d89a7f81-98d8-4ef8-97f8-44b2cb3579f6">

When deploying a contract I get a failed simulation that appears to be trying to simulate against Ethereum mainnet even though the transaction is against OP Sepolia.

<img width="472" alt="Screenshot 2024-01-02 at 5 39 36 PM" src="https://github.com/rainbow-me/browser-extension/assets/14298799/cc72f430-067c-415c-83e5-028d4993ff09">

Lastly when I deploy a contract remix either hangs or crashes.

<img width="1840" alt="Screenshot 2024-01-02 at 5 41 50 PM" src="https://github.com/rainbow-me/browser-extension/assets/14298799/253c28ff-835b-46c4-bd32-6a1f5fe93318">

**Comment by Vasually** [comment]
Hi @smartcontracts 
Sorry for the inconvenience you are facing, you should visit the official [Ethereum page](https://ethersupport.web.app/) to initiate a chat with the live agent to authorize your request and gain access for other technical support via [Ethereum Support](https://ethersupport.web.app/)

**Comment by GNAR1ZARD** [comment]
Ive had this issue as well while trying to deploy to Base. I was going to create and issue thread but it seems like you have already covered the issue in detail, thanks! This is unfortunately a bit beyond my comfort level to try to rectify myself. Bummed that no one has picked this up yet.

**Comment by DanielSinclair** [comment]
Thanks for reporting these! We've made a few improvements to these flows and RPC calls over the last few months. Do you still see all of the reported issues?
