### ISSUE TITLE
sendAsync method doesn't follow SafeEventEmitter

### ISSUE THREAD

**Issue by vanya2h** [rainbow-me/browser-extension#1303]
I'm using json rpc middlewares with https://github.com/MetaMask/eth-json-rpc-middleware and it seems working with the most of injectable wallets. And recently I've discovered it doesn't work with Rainbow's so I dived deeper and discovered that your sendAsync method doesn't accept second argument - callback and instead returns just promise. 

Example of problem:
```
window.rainbow.sendAsync(jsonRpcRequest, (err, jsonRpcResponse) => {
 // it'll never happen, callback is never called
})
```

**Comment by DanielSinclair** [comment]
@vanya2h Thanks for reporting this! This was fixed and released a few weeks back with additions to our window provider described here: https://github.com/rainbow-me/provider/pull/9
