### ISSUE TITLE
Can't connect Rainbow browser-extension on DAPPs using rainbowkit

### ISSUE THREAD

**Issue by tomasmcm** [rainbow-me/browser-extension#1310]
On most DAPPs, the rainbow browser-extension can connect using the metamask option (e.g.: https://app.aave.com/), however, it seems that on DAPPs that are using rainbowkit, unless they enable "rainbow" as a wallet, the browser extension cannot connect using the "metamask" option (it just shows a link to download the extension) (e.g: https://app.stcelo.xyz/stake).
Since you develop both softwares, is there a way to make one of the other allow the extension to connect as if it was metamask?
Thanks!

**Comment by DanielSinclair** [comment]
This is now resolved with RainbowKit v2 and above
