### ISSUE TITLE
`accountsChanged` event is not emitted on disconnect

### ISSUE THREAD

**Issue by ardislu** [rainbow-me/browser-extension#1386]
**Steps to reproduce the issue:**
1. Host this HTML file on a local web server and open it in a web browser:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>accountsChanged Test</title>
</head>

<body>
  <script>
    const wallets = [];
    window.addEventListener('eip6963:announceProvider', e => wallets.push(e.detail));
    window.dispatchEvent(new Event('eip6963:requestProvider'));

    for (const wallet of wallets) {
      wallet.provider.addListener?.('accountsChanged', console.log) ?? wallet.provider.on('accountsChanged', console.log);
    }
  </script>
</body>

</html>
```

2. Connect your wallet using the wallet UI.
3. Disconnect your wallet using the wallet UI.

**Expected result:** two `accountsChanged` events are emitted. One upon connection and one upon disconnection. The DevTools console log should look like this:

```plaintext
> ['0xaaa..aaa']
> []
```

**Actual result:** only one `accountsChanged` event is emitted, upon connection. The DevTools console log looks like this:

```plaintext
> ['0xaaa..aaa']
```

---

Here's the relevant part of [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193):

>  # accountsChanged
> If the accounts available to the Provider change, the Provider **MUST** emit the event named `accountsChanged` with value `accounts: string[]`, containing the account addresses per the `eth_accounts` Ethereum RPC method.
> 
>The “accounts available to the Provider” change when the return value of `eth_accounts` changes.

Since the return value of `eth_accounts` changes when the wallet disconnects (from an array with 1 address to an empty array), the `accountsChanged` event must be emitted. 

I performed the above steps with MetaMask and Brave Wallet, and they both emit 2 events as expected.

**Comment by estebanmino** [comment]
@ardislu thanks, makes sense
