### ISSUE TITLE
[bug] Can't detect `favicon.ico` when connecting

### ISSUE THREAD

**Issue by zwergdev** [rainbow-me/browser-extension#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0

### wagmi Version

2.5.6

### Current Behavior

![Resume Group 1](https://github.com/rainbow-me/rainbowkit/assets/132711041/19a34629-ee3b-4abc-a05a-d35628ca8b73)

### Expected Behavior

Normal icon of some site

<img width="307" alt="Screenshot 2024-03-13 at 16 33 03" src="https://github.com/rainbow-me/rainbowkit/assets/132711041/2714ebe0-e7dd-4c1e-805b-f582d528c65f">

### `appIcon` using `getDefaultConfig`

**I use real domain, icon URL and project ID**

```
export const config = getDefaultConfig({
  ...
  appUrl: 'https://real-domain.com,
  appIcon: 'https://real-domain.com/icon.png',
  projectId: '01001001110100100010010',
  ...
})
```

### Anything else?

I did not find any information regarding the icon even in the open repository of [rainbowkit.com](https://www.rainbowkit.com/)

**Comment by DanielSinclair** [comment]
@zwergdev Do you happen to have a test deployment URL we can look at and test? We index these favicons with DuckDuckGo with this structure. There could simply be propagation delays, but can investigate as well. `https://icons.duckduckgo.com/ip3/${dapp_domain}.ico`

**Comment by zwergdev** [comment]
@DanielSinclair Thanks for response. I know about indexing through duckduck. So, I see my icon using icons.duckduckgo link.
