### ISSUE TITLE
Can Mantle's network be added?

### ISSUE THREAD

**Issue by Rowen-S** [rainbow-me/browser-extension#1450]
I have seen wallet plugins that support bybit wallet, but the network does not support mantle, mantle is a second layer with a large number of users, looking forward to adding it.

network Name: Mantle
rpc url: https://mantle.public-rpc.com/
chain ID: 5000
Currency symbol: MNT
Blocks the browser: https://explorer.mantle.xyz/

**Comment by DanielSinclair** [comment]
@Rowen-S Yes, Rainbow does support Mantle and other Custom Networks.

In the Settings menu, select Networks, Add Custom Network, and begin typing Mantle. We have an auto-fill available with Mantle's network information, but you can always amend these fields.

<img width="358" alt="Screenshot 2024-04-06 at 1 31 30 AM" src="https://github.com/rainbow-me/browser-extension/assets/4412473/cf1b267d-0b9a-40ab-b321-efc19bed18c8">

<img width="359" alt="Screenshot 2024-04-06 at 1 31 38 AM" src="https://github.com/rainbow-me/browser-extension/assets/4412473/3a6a9c73-18c4-432e-b20c-9435d8c9c622">

**Comment by Rowen-S** [comment]
![image](https://github.com/rainbow-me/browser-extension/assets/50318674/951169cb-0a1c-4746-b744-50f75c2ade53)
Whether it can be added to the default netlist
