### ISSUE TITLE
wallet_switchEthereumChain Does not work with custom networks #5620

### ISSUE THREAD

**Issue by julia-script** [rainbow-me/browser-extension#1489]
Apparently, `wallet_switchEthereumChain` doesn't work with networks added through `wallet_addEthereumChain`
is this intentional?

##  Steps
1. Add a custom network 
```
window.rainbow.request({
    "method": "wallet_addEthereumChain",
    "params": [
        {
            "chainId": "0x2329",
            "chainName": "Evmos",
            "nativeCurrency": {
                "decimals": 18,
                "name": "Evmos",
                "symbol": "EVMOS"
            },
            "rpcUrls": [
                "http://localhost:3000/api/eth-json-rpc/evmos"
            ],
            "blockExplorerUrls": [
                "https://escan.live"
            ]
        }
    ]
})
```
(this works, this adds the network to my wallet, it doesn't auto switch to it after that though as is the behavior in other wallets)
2. Try to switch to the network
```
window.rainbow.request({
    "method": "wallet_switchEthereumChain",
    "params": [
        {
            "chainId": "0x2329",
        }
    ]
})
```

I get the following error

```
{
    "name": "Invalid Request",
    "message": "Chain Id not supported",
    "code": -32600
}
```

digging the code a little bit it seems that only what's in this list here is supported, is that correct?
https://github.com/rainbow-me/browser-extension/blob/aab2ad59530a1356667aab51b144cb774877a36b/src/core/references/index.ts#L228

`wallet_addEthereumChain` seems to check for a `featureFlags.custom_rpc` flag, but `wallet_switchEthereumChain` right below it doesnt
https://github.com/rainbow-me/provider/blob/586aa46965b41173bd071d7ca2bdccf70ef10b0c/src/handleProviderRequest.ts#L239

**Comment by estebanmino** [comment]
this was fixed yesterday, coming out in the next release

**Comment by estebanmino** [comment]
thanks for the report 🚀

**Comment by julia-script** [comment]
oh, that was a quick one, thanks :)

**Comment by julia-script** [comment]
Quick question, when is next release scheduled to?

**Comment by DanielSinclair** [comment]
This fix was released on 04/17. Let us know if any issues persist!
