### ISSUE TITLE
Error: connect ETIMEDOUT 205.186.152.122:443

### ISSUE THREAD

**Issue by MarkTangCd** [rainbow-me/browser-extension#1511]
<img width="610" alt="image" src="https://github.com/rainbow-me/browser-extension/assets/93690147/d47fcfe2-098c-473b-b2c6-da0bb42d2a94">

I always get this error when I ran "yarn setup" command.

Node.js version: v18.16.1

**Comment by DanielSinclair** [comment]
@MarkTangCd Looks like you're missing some ENV keys that are used to introspect our GraphQL service. We unfortunately don't provide external support or API keys, so it will be difficult for you to build the project independently.
