### ISSUE TITLE
Add ability to change/remove cmd+E shortcut

### ISSUE THREAD

**Issue by Cygnusfear** [rainbow-me/browser-extension#1530]
conflicts with other browser extensions

**Comment by DanielSinclair** [comment]
@Cygnusfear Which extensions are you see a conflict with? Cmd+E actually shouldn't be registered by Rainbow. We do offer Alt+Shift+R however to trigger Rainbow to open. Do you mind taking a screenshot of `chrome://extensions/shortcuts` to show the conflicts?###

**Comment by Cygnusfear** [comment]
I think this issue can be closed; as you mentioned the alt-shift-r shortcut
is assigned to Rainbow correctly.

This seems to have been an Arc browser issue: I'm using Arc and before a
recent update this would pull up my first extension (I am assuming, as it
now pops up a list of extensions, and pressing ESC now opens rainbow (the
first listed extension)).
