### ISSUE TITLE
Cannot find browser-extensions-env repository

### ISSUE THREAD

**Issue by TTNguyenDev** [rainbow-me/browser-extension#1549]
### 3. Set up your .env file

Run `touch .env`, head to the `browser-extension-env` repository, and copy + paste the variables into your `.env`

**Comment by DanielSinclair** [comment]
The repo's build-time env variables are currently protected, and we don't plan to expose access to our services and infrastructure publicly. You can always build locally by supplying your own env (RPCs, etc.) by referencing the `.env.example` file and our types here: https://github.com/rainbow-me/browser-extension/blob/master/.env.d.ts

**Comment by TTNguyenDev** [comment]
so which one is require?  @DanielSinclair
