### ISSUE TITLE
run rainbow locally

### ISSUE THREAD

**Issue by tuanh2000** [rainbow-me/browser-extension#1551]
`
LavaMoat generating policy from entry "/Users/henry/Desktop/Backend/browser-extension/scripts/webpack.js"...
⚠️  Potentially Incompatible code detected in package "webpack" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/webpack/lib/serialization/ObjectMiddleware.js":
  645 |                                                                 }
  646 |                                                                 if (!loaded) {
> 647 |                                                                         require(request);
      |                                                                 ^^^^^^^^^^^^^^^^ dynamic require
  648 |                                                                 }
  649 |
  650 |                                                                 loadedRequests.add(request);
lavamoat - unable to resolve "pnpapi" from "/Users/henry/Desktop/Backend/browser-extension/node_modules/webpack/node_modules/enhanced-resolve/lib/ResolverFactory.js"
⚠️  Potentially Incompatible code detected in package "webpack" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/webpack/lib/ProgressPlugin.js":
  410 |                                                                 currentLoader = loader.loader;
  411 |                                                                 update();
> 412 |                                                                 require(loader.loader);
      |                                                         ^^^^^^^^^^^^^^^^^^^^^^ dynamic require
  413 |                                                         }
  414 |                                                 }
  415 |                                                 if (currentLoader) {
⚠️  Potentially Incompatible code detected in package "webpack>loader-runner" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/loader-runner/lib/loadLoader.js":
  17 |  } else {
  18 |          try {
> 19 |                  var module = require(loader.path);
     |                              ^^^^^^^^^^^^^^^^^^^^ dynamic require
  20 |          } catch(e) {
  21 |                  // it is possible for node to choke on a require if the FD descriptor
  22 |                  // limit has been reached. give it a chance to recover.
⚠️  Potentially Incompatible code detected in package "webpack>browserslist" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/browserslist/node.js":
  174 |       checkExtend(name)
  175 |     }
> 176 |     var queries = require(require.resolve(name, { paths: ['.', ctx.path] }))
      |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ dynamic require
  177 |     if (queries) {
  178 |       if (Array.isArray(queries)) {
  179 |         return queries
  195 |       checkExtend(name)
  196 |     }
> 197 |     var stats = require(require.resolve(
      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 198 |       path.join(name, 'browserslist-stats.json'),
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 199 |       { paths: ['.'] }
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 200 |     ))
      | ^^^^^^ dynamic require
  201 |     return normalizeStats(data, stats)
  202 |   },
  203 |
  246 |       var compressed
  247 |       try {
> 248 |         compressed = require('caniuse-lite/data/regions/' + code + '.js')
      |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ dynamic require
  249 |       } catch (e) {
  250 |         throw new BrowserslistError("Unknown region name " + code + ".")
  251 |       }
  266 |     var compressed
  267 |     try {
> 268 |       compressed = require('caniuse-lite/data/features/' + name + '.js')
      |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ dynamic require
  269 |     } catch (e) {
  270 |       throw new BrowserslistError("Unknown feature name " + name + ".")
  271 |     }
lavamoat - unable to resolve "uglify-js" from "/Users/henry/Desktop/Backend/browser-extension/node_modules/terser-webpack-plugin/dist/utils.js"
lavamoat - unable to resolve "uglify-js/package.json" from "/Users/henry/Desktop/Backend/browser-extension/node_modules/terser-webpack-plugin/dist/utils.js"
lavamoat - unable to resolve "@swc/core" from "/Users/henry/Desktop/Backend/browser-extension/node_modules/terser-webpack-plugin/dist/utils.js"
lavamoat - unable to resolve "@swc/core/package.json" from "/Users/henry/Desktop/Backend/browser-extension/node_modules/terser-webpack-plugin/dist/utils.js"
lavamoat - unable to resolve "pnpapi" from "/Users/henry/Desktop/Backend/browser-extension/node_modules/esbuild/lib/main.js"
⚠️  Potentially Incompatible code detected in package "webpack>terser-webpack-plugin>jest-worker" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/index.js":
  66 |
  67 |   if (!exposedMethods) {
> 68 |     const module = require(workerPath);
     |                   ^^^^^^^^^^^^^^^^^^^ dynamic require
  69 |
  70 |     exposedMethods = Object.keys(module).filter(
  71 |       // @ts-expect-error: no index
⚠️  Potentially Incompatible code detected in package "@vanilla-extract/vite-plugin>@vanilla-extract/integration" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/@vanilla-extract/integration/dist/vanilla-extract-integration.cjs.prod.js":
  272 |     const {
  273 |       name
> 274 |     } = require(packageJsonPath);
      |        ^^^^^^^^^^^^^^^^^^^^^^^^ dynamic require
  275 |
  276 |     return {
  277 |       name,
⚠️  Potentially Incompatible code detected in package "@vanilla-extract/vite-plugin>@vanilla-extract/integration" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/@vanilla-extract/integration/dist/vanilla-extract-integration.cjs.dev.js":
  272 |     const {
  273 |       name
> 274 |     } = require(packageJsonPath);
      |        ^^^^^^^^^^^^^^^^^^^^^^^^ dynamic require
  275 |
  276 |     return {
  277 |       name,
lavamoat - unable to resolve "babel-register" from "/Users/henry/Desktop/Backend/browser-extension/node_modules/dotenv-webpack/index.js"
lavamoat - unable to resolve "./src" from "/Users/henry/Desktop/Backend/browser-extension/node_modules/dotenv-webpack/index.js"
⚠️  Potentially Incompatible code detected in package "ts-loader" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/ts-loader/dist/instances.js":
  225 |     else if (typeof customerTransformers === 'string') {
  226 |         try {
> 227 |             customerTransformers = require(customerTransformers);
      |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ dynamic require
  228 |         }
  229 |         catch (err) {
  230 |             throw new Error(Failed to load customTransformers from "${instance.loaderOptions.getCustomTransformers}": ${err instanceof Error ? err.message : 'unknown error'});
⚠️  Potentially Incompatible code detected in package "ts-loader" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/ts-loader/dist/compilerSetup.js":
   9 |     let compilerCompatible = false;
  10 |     try {
> 11 |         compiler = require(loaderOptions.compiler);
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ dynamic require
  12 |     }
  13 |     catch (e) {
  14 |         errorMessage =
⚠️  Potentially Incompatible code detected in package "typescript" file "/Users/henry/Desktop/Backend/browser-extension/node_modules/typescript/lib/typescript.js":
  3096 |       try {
  3097 |         const etwModulePath = process.env.TS_ETW_MODULE_PATH ?? "./node_modules/@microsoft/typescript-etw";
> 3098 |         etwModule =   require(etwModulePath);
       |                      ^^^^^^^^^^^^^^^^^^^^^^ dynamic require
  3099 |       } catch (e) {
  3100 |         etwModule = void 0;
  3101 |       }
  6267 |               try {
  6268 |                 const modulePath = resolveJSModule(moduleName, baseDir, nodeSystem);
> 6269 |                 return { module:   require(modulePath), modulePath, error: void 0 };
       |                                   ^^^^^^^^^^^^^^^^^^^ dynamic require
  6270 |               } catch (error2) {
  6271 |                 return { module: void 0, modulePath: void 0, error: error2 };
  6272 |               }
LavaMoat wrote policy to "/Users/henry/Desktop/Backend/browser-extension/lavamoat/build-webpack/policy.json"
`

I got this error when run "yarn setup"

**Comment by DanielSinclair** [comment]
These are expected warnings currently. This product is opensource for code auditing and community review, so it will be challenging to build locally for other purposes. Please keep GitHub Issues to product bugs, vulnerabilities, or missing support for a particular standard.
