### ISSUE TITLE
bug: token tx TO is the same as Token Contract address

### ISSUE THREAD

**Issue by Cygnusfear** [rainbow-me/browser-extension#1553]
As a user I expect token TX to display the receiving address, not the token contract

**Comment by DanielSinclair** [comment]
@Cygnusfear Can you provider a screenshot or clarify which part of the extension you're referencing here?

**Comment by Cygnusfear** [comment]
[image: Screenshot 2024-05-28 at 05.40.16.png]

The expected TO should be the recipient address / address book contact I'm
sending the token to like a normal TX.
The expected TO in activity should also display the recipient address /
contact.

The current experience as a user is very problematic and dangerous, because
it seems like I've sent the tokens to the token contract (a very common
problem, known to be the cause for a huge loss of funds).

This is also spectacularly unsafe because now users are forced to check the
various L2 blockchain explorers, which all work very differently, to even
get an idea of where the transaction went. Which opens them up to address
poisoning. There's more downstream issues from here but I'd have to
elaborate on a call.

While scrolling my activity all my activity disappeared, for all accounts,
(rpc issue? another bug?) because this 'TO' is also used in the general
activity display which I was trying to screenshot for you.
[image: Screenshot 2024-05-28 at 05.44.27.png]

**Comment by DanielSinclair** [comment]
It looks like GitHub dropped the screenshots when sending via email. Can you try to upload them on the Web?

**Comment by Cygnusfear** [comment]
Ah, yes of course:

![unnamed](https://github.com/rainbow-me/browser-extension/assets/2925132/6ccd2d72-70b7-4ffe-b01f-85caa3280692)
[image: Screenshot 2024-05-28 at 05.40.16.png]

![image](https://github.com/rainbow-me/browser-extension/assets/2925132/d9b6f159-03fa-47f9-b00d-26967b354a49)
[image: Screenshot 2024-05-28 at 05.44.27.png]

**Comment by DanielSinclair** [comment]
@Cygnusfear Thanks for highlighting! I agree that this display issue is a problem, and we'll get this fixed this week

**Comment by DanielSinclair** [comment]
This is resolved in our release going out today. Thanks again!
