### ISSUE TITLE
Content Security Policy Issues Interfering With Connectivity

### ISSUE THREAD

**Issue by RioCasanova** [rainbow-me/browser-extension#1686]
# Host of various issues due to CSP error

## Steps to Replicate

I followed what was outlined in the README:

- using Node v 20
- used `yarn setup`
- created a .env file - CAVEAT: I COULD NOT FIND THE AFOREMENTIONED REPO IN STEP 3: browser-extension-env
- I imported the extension and selected the build folder (Brave & Chrome)
- used `yarn dev`

## Error Details

1. [Imgix] Image signing disabled. Please ensure you have specified both IMGIX_DOMAIN and IMGIX_TOKEN inside your .env.
2. Error Getting Remote Config
3. Refused to connect to 'XXXXXXX' because it violates the following Content Security Policy directive: ***contents***
4. Many others

## Help

Please tell me how I might further diagnose the core issue, where to look, or maybe I am missing something quite obvious, anything helps, thank you.

**Comment by DanielSinclair** [comment]
@RioCasanova These are errors that result from missing API keys. Rainbow is powered by quite a few services and upstream vendors, so you'll need to populate most of the ENV variables to build and run locally. We're open source for code review and auditing, but it will be headache for third party devs to fork the project and build locally. https://github.com/rainbow-me/browser-extension/blob/master/.env.example
