### ISSUE TITLE
Bare minimum environment variables to run the wallet locally

### ISSUE THREAD

**Issue by thedevbirb** [rainbow-me/browser-extension#1729]
In the "Getting Started" section of the README it is suggested to head over the `browser-extension-env` repository:

https://github.com/rainbow-me/browser-extension/blob/439d9e410d24b547c98a6af0a4301e562392dd2e/README.md?plain=1#L79

However, https://github.com/rainbow-me/browser-extension-env doesn't exist or it is private. 

What are the environment variables needed to play with the locally developed wallet in the browser? By using the what's in the `.env.example` file and building at commit 439d9e410d24b547c98a6af0a4301e562392dd2e I cannot:
- import a wallet from an existing mnemonic -- it remains stuck on the fetching accounts
- import a custom chain because querying the RPC fails with "The provided RPC endpoint is not responding" even if it works when running the production version of the extension.

Thanks for the help!

**Comment by DanielSinclair** [comment]
`.env.example` us up-to-date with necessary ENV variables. We are opensource for auditing purposes, so it will be a bit difficult to build locally without access to some of our endpoints. It sounds like you're using an invalid RPC in this case.
