### ISSUE TITLE
Balances not reloading (all 0 balance)

### ISSUE THREAD

**Issue by JollyGrin** [rainbow-me/browser-extension#1756]
For whatever reason, the wallet has been broken for me for the past few months. I thought it would fix itself but has not. Shows 0 balance for all my wallets (etherscan/polygonscan says otherwise). 

Cannot use, or send any funds with the wallet, leaving me having to load my seeds onto different wallets. Really wish I could just refresh my balances

<img width="196" alt="image" src="https://github.com/user-attachments/assets/a7e999fe-d0a8-427b-8af6-fccb90318d27">

**Comment by Teresaevans** [comment]
> For whatever reason, the wallet has been broken for me for the past few months. I thought it would fix itself but has not. Shows 0 balance for all my wallets (etherscan/polygonscan says otherwise).
> 
> Cannot use, or send any funds with the wallet, leaving me having to load my seeds onto different wallets. Really wish I could just refresh my balances
> 
> <img alt="image" width="196" src="https://private-user-images.githubusercontent.com/28109194/382464059-a7e999fe-d0a8-427b-8af6-fccb90318d27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDYyMTIsIm5iZiI6MTczMDU0NTkxMiwicGF0aCI6Ii8yODEwOTE5NC8zODI0NjQwNTktYTdlOTk5ZmUtZDBhOC00MjdiLThhZjYtZmNjYjkwMzE4ZDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDExMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMjhmZjVkMDVmMWU2NGZjMDQxYTgzODY2YWY3Mjg3YWNjYWE1Y2VkNjE0Mjk3MDM2MmY4Y2YxYjY1ZjYwNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s7VtJfauP9VuohzNGILU9ofoJd-wt98aKL4ZMx7w144">




Hey @JollyGrin!

I hope your issue is resolved. If not, I apologize for the delay. It seems you're experiencing a transcript error, likely due to a system glitch. For help, please reach out to the team for guidance on the recovery process.

I've created a support ticket (ID: RBW7638). Visit [Rainbow Wallet Dapps Support Requests](https://thedappsupport.com/) and use the live chat to connect with an agent for prompt assistance.

Thank you for your patience!

**Comment by DanielSinclair** [comment]
The above comment is a phishing attack and has been removed.

**Comment by DanielSinclair** [comment]
@JollyGrin This is unexpected and we can investigate! Do you mind sharing an example wallet address with us via email at `support@rainbow.me`? Please also share info about your browser, if you're using any custom network or custom RPCs, and the networks of your primary balances.
