### ISSUE TITLE
Improve auditability by removing / replacing dependencies

### ISSUE THREAD

**Issue by paulmillr** [rainbow-me/browser-extension#991]
Auditing rainbow is complicated, because it's too big. Size can easily be reduced by removing and replacing dependencies.

1. ethers v5 could be replaced with v6 or viem. They both use better cryptography and native bigints instead of bn.js and bignumber.js. Viem is friendly to wagmi, which you are already using.
2. bignumber.js direct dep can be removed in favor of native bigints
3. buffer can be replaced with native uint8array

Probably a deep dive into all deps would reveal hundreds of kilobytes of unused code.

**Comment by DanielSinclair** [comment]
@paulmillr Thanks for having a look! We had actually built much of our keychain before viem and ethers v6, and ethers v5 is still our go-to at Rainbow for a little while yet (and many other projects including MetaMask). A migration to the newer frameworks with better tree-shaking and deprecating BigNumber is definitely something we'll work towards. If you happen to see any other unused or bloated dependencies, definitely let us know; we want to continue to improve cold boot times for short-lived workers in the Manifest v3 world.

**Comment by paulmillr** [comment]
https://github.com/rainbow-me/browser-extension/blob/ef4b4ed75b0963ebbc4a4ec3bf1b4242acfc0e77/src/core/keychain/keychainTypes/keyPairKeychain.ts#L3

This basically says you're using `elliptic` for secp256k1 signatures, which is pretty bad, even though it's sandboxed by lavamoat. Elliptic had 2 CVEs and after that it became basically unmaintained.

The suggestion is to upgrade at least these `Mnemonic` and `HDNode` methods to audited https://github.com/ethereum/js-ethereum-cryptography (used in ethers v6) or directly to scure-bip32 / scure-bip39 which are small and also audited

**Comment by DanielSinclair** [comment]
@paulmillr Thanks for highlighting — we're on it and the team is beginning the upgrade for Ethers v6 this week
